### Get all products
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "iMac Pro 2020",
  "price": 2099
}

### Get a product by id
GET http://localhost:3000/products/60f42abd2a913a2c8bfd8adc

### Update a product by id
PATCH http://localhost:3000/products/60f42abd2a913a2c8bfd8adc
Content-Type: application/json

{
  "name": "iMac Pro"
}

### Delete a product by id
DELETE http://localhost:3000/products/60f42abd2a913a2c8bfd8adc

### Home route
GET http://localhost:3000/

### 404 Test
GET http://localhost:3000/abc

### Test
POST http://localhost:3000/test
Content-Type: application/json

{
  "name": "iMacPro",
  "price": 4999
}

### Test
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMacPro&price=4999
